### ISSUE TITLE
Market Data api issue

### ISSUE THREAD

**Issue by cooldeep25** [bitcoincoltd/bitexthai#1]
Hi, 
The Market data api endpoint get request throws error 403 forbidden. 

https://bx.in.th/info/api/

what could be the issue?

**Comment by bt7411** [comment]
Try 

https://bx.in.th/api/

**Comment by cooldeep25** [comment]
Sorry, I am trying the same endpoint but returns the 403 forbidden error. May be am I missing something? Do I need to provide any headers or parameters?

**Comment by cooldeep25** [comment]
The api responds with the captcha validation challenge.

**Comment by cooldeep25** [comment]
The api responds with the captcha validation challeng for get request of endpoint, not sure if I have to provide additional inputs

**Comment by bt7411** [comment]
I think that url is an open API and returns a list of current prices. In Google Sheets you can run the Google Script:
`function getBX() {
  var response = UrlFetchApp.fetch("https://bx.in.th/api/");
  Logger.log(response );
}
`
Then View Logs and you should see the response.

**Comment by cooldeep25** [comment]
thank you, it works
